name: npt
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2024.3.11
  - cudatoolkit=10.1.243
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuv=1.44.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - openssl=3.0.13
  - python=3.8.19
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - typing_extensions=4.9.0
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.14.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cachetools==4.2.4
      - catboost==0.26
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - comm==0.2.2
      - configparser==6.0.1
      - cycler==0.12.1
      - cython==3.0.9
      - dataclasses==0.6
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - dotmap==1.3.23
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fairseq==0.10.2
      - fastjsonschema==2.19.1
      - filelock==3.13.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.6
      - gpytorch==1.4.2
      - grpcio==1.62.1
      - huggingface-hub==0.0.8
      - hydra-core==1.3.2
      - idna==3.6
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - install==1.3.5
      - ipykernel==6.29.3
      - ipython==8.12.3
      - ipython-genutils==0.2.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - json5==0.9.24
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyter-server==1.24.0
      - jupyterlab==3.1.0a11
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.4
      - kiwisolver==1.4.5
      - lightgbm==3.2.1
      - lightning-utilities==0.11.0
      - line-profiler==3.3.0
      - littleutils==0.2.2
      - llvmlite==0.35.0
      - lxml==5.1.0
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.4.2
      - matplotlib-inline==0.1.6
      - memory-profiler==0.58.0
      - mistune==3.0.2
      - multidict==6.0.5
      - nbclassic==0.5.6
      - nbclient==0.10.0
      - nbconvert==7.16.2
      - nbformat==5.10.3
      - nest-asyncio==1.6.0
      - notebook==6.4.0
      - notebook-shim==0.2.4
      - numba==0.52.0
      - numpy==1.20.3
      - oauthlib==3.2.2
      - ogb==1.3.1
      - omegaconf==2.3.0
      - outdated==0.2.2
      - packaging==24.0
      - pandas==1.2.4
      - pandocfilters==1.5.1
      - parso==0.8.3
      - pathtools==0.1.2
      - patool==1.12
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pip==24.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.0
      - plotly==5.20.0
      - portalocker==2.8.2
      - prometheus-client==0.20.0
      - promise==2.3
      - prompt-toolkit==3.0.43
      - protobuf==3.17.2
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyaml==23.12.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycodestyle==2.7.0
      - pycparser==2.21
      - pydeprecate==0.3.0
      - pygments==2.17.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - pytorch-lightning==1.3.4
      - pytorch-tabnet==3.1.1
      - pytz==2024.1
      - pyyaml==5.4.1
      - pyzmq==25.1.2
      - qhoptim==1.0.0
      - referencing==0.34.0
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==1.4.0
      - rpds-py==0.18.0
      - rsa==4.9
      - sacrebleu==2.4.1
      - sacremoses==0.1.1
      - scikit-learn==0.24.2
      - scikit-optimize==0.8.1
      - scipy==1.10.1
      - seaborn==0.11.1
      - send2trash==1.8.2
      - sentry-sdk==1.43.0
      - setproctitle==1.3.3
      - shortuuid==1.0.13
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - subprocess32==3.5.4
      - tabnet==0.1.6
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.5.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.2
      - terminado==0.18.1
      - threadpoolctl==3.4.0
      - tinycss2==1.2.1
      - tokenizers==0.10.3
      - torch==1.8.1
      - torchmetrics==1.2.1
      - torchvision==0.9.1
      - tornado==6.4
      - tqdm==4.61.0
      - traitlets==5.14.2
      - transformers==4.6.1
      - urllib3==2.2.1
      - wandb==0.16.4
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - wget==3.2
      - xgboost==1.4.2
      - yarl==1.9.4
      - zipp==3.18.1
