name: npt
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=10.1
  - pytorch=1.7
  - pip
  - pip:
    - catboost==0.26
    - dotmap==1.3.23
    - fairseq==0.10.2
    - gpytorch==1.4.2
    - jupyterlab==3.1.0a11
    - lightgbm==3.2.1
    - line-profiler==3.3.0
    - matplotlib==3.4.2
    - memory-profiler==0.58.0
    - notebook==6.4.0
    - numba==0.52.0
    - numpy==1.20.3
    - ogb==1.3.1
    - pandas==1.2.4
    - patool==1.12
    - protobuf==3.17.2
    - pycodestyle==2.7.0
    - pytorch-lightning==1.3.4
    - pytorch-tabnet==3.1.1
    - qhoptim==1.0.0
    - scikit-learn==0.24.2
    - scikit-optimize==0.8.1
    - seaborn==0.11.1
    - tabnet==0.1.6
    - tensorboard==2.5.0
    - tensorboardX==2.2
    - torchvision==0.9.1
    - tqdm==4.61.0
    - transformers==4.6.1
    - wandb==0.16.4
    - wget==3.2
    - xgboost==1.4.2
