### Ablations

## Protein
# 5-fold
python run.py --data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000  --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key protein__bs_2048__feature_mask__label_mask --exp_n_runs 5
# No Label Masking
python run.py --data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key protein__ablation__bs_2048__feature_mask
# No Feature Masking
python run.py --data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.0, val=0, test=0)" --exp_tradeoff 0 --exp_tradeoff_annealing constant --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key protein__ablation__bs_2048__label_mask
# No Feature Masking, No Label Masking
python run.py --data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.0, val=0, test=0)" --exp_tradeoff 0 --exp_tradeoff_annealing constant --exp_cache_cadence 1 --model_checkpoint_key protein__ablation__bs_2048
# 8 -> 4 layers
python run.py --data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 4 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key protein__ablation__bs_2048__feature_mask__label_mask__layers_4
# 8 -> 4 heads
python run.py --data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 4 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key protein__ablation__bs_2048__feature_mask__label_mask__heads_4
# Fix Tradeoff to 0.5
python run.py --data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 0.5 --exp_tradeoff_annealing constant --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key protein__ablation__bs_2048__feature_mask__label_mask__tradeoff_0.5
# No SSL
python run.py --data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key protein__ablation__bs_2048__feature_mask__label_mask__no_ssl --model_is_semi_supervised False
# BERT Feature Aug to 0.5
python run.py --data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.5, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key protein__ablation__bs_2048__feature_mask_0.5__label_mask
# BERT Label Aug to 0.5
python run.py --data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key protein__ablation__bs_2048__feature_mask__label_mask_0.5
# 8 -> 16 layers
python run.py --data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 16 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key protein__ablation__bs_2048__feature_mask__label_mask__layers_16
# 8 -> 16 heads
python run.py --data_set protein --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 16 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 400000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key protein__ablation__bs_2048__feature_mask__label_mask__heads_16


## Boston
# Default
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask__label_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# No Label Masking
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# No Feature Masking
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.0, val=0, test=0)" --exp_tradeoff 0 --exp_tradeoff_annealing constant --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__label_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# No Feature Masking, No Label Masking
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.0, val=0, test=0)" --exp_tradeoff 0 --exp_tradeoff_annealing constant --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 8 -> 4 layers
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 4 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask__label_mask__layers_4 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 8 -> 4 heads
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 4 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask__label_mask__heads_4 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Fix Tradeoff to 0.5
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 0.5 --exp_tradeoff_annealing constant --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask__label_mask__tradeoff_0.5 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# No SSL
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask__label_mask__no_ssl --model_is_semi_supervised False --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# BERT Feature Aug to 0.5
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.5, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask_0.5__label_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# BERT Label Aug to 0.5
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask__label_mask_0.5 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 8 -> 16 layers
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 16 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask__label_mask__layers_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 8 -> 16 heads
python run.py --data_set boston-housing --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 16 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000 --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__ablation__bs_-1__feature_mask__label_mask__heads_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2