### UCI Small Data

## Boston
# Default
python run.py --data_set boston-housing --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key boston__bs_-1__feature_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Feature Mask 0.20
python run.py --data_set boston-housing --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.2, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key boston__bs_-1__feature_mask_20perc --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Label Mask 0.50
python run.py --data_set boston-housing --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 4000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__bs_-1__feature_mask__label_mask_50 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Label Mask 0.10
python run.py --data_set boston-housing --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.1, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key boston__bs_-1__feature_mask__label_mask_10 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 16 Heads
python run.py --data_set boston-housing --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 16 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key boston__bs_-1__feature_mask__heads_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 16 Layers
python run.py --data_set boston-housing --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 16 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key boston__bs_-1__feature_mask__layers_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 16 Heads, 16 Layers
python run.py --data_set boston-housing --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 16 --model_stacking_depth 16 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key boston__bs_-1__feature_mask__heads_16__layers_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Cosine Cyclic LR Schedule
python run.py --data_set boston-housing --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_num_total_steps 2000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key boston__bs_-1__feature_mask__cosine_cyclic --exp_scheduler=cosine_cyclic --exp_optimizer_warmup_proportion 0.2 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2

## Concrete
# Default
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Feature Mask 0.20
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.2, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask_20perc --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Label Mask 0.50
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask__label_mask_50 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Label Mask 0.10
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.1, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask__label_mask_10 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 16 Heads
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 16 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask__heads_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 16 Layers
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 16 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask__layers_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 16 Heads, 16 Layers
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 16 --model_stacking_depth 16 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask__heads_16__layers_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Cosine Cyclic LR Schedule
python run.py --data_set concrete --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key concrete__bs_-1__feature_mask__cosine_cyclic --exp_scheduler=cosine_cyclic --exp_optimizer_warmup_proportion 0.2 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2

## Yacht
# Default
python run.py --data_set yacht --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Feature Mask 0.20
python run.py --data_set yacht --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.2, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask_20perc --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Label Mask 0.50
python run.py --data_set yacht --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask__label_mask_50 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Label Mask 0.10
python run.py --data_set yacht --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.1, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask__label_mask_10 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 16 Heads
python run.py --data_set yacht --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 16 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask__heads_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 16 Layers
python run.py --data_set yacht --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 16 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask__layers_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 16 Heads, 16 Layers
python run.py --data_set yacht --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 16 --model_stacking_depth 16 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask__heads_16__layers_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Cosine Cyclic LR Schedule
python run.py --data_set yacht --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_num_total_steps 10000  --exp_gradient_clipping 1 --exp_batch_size -1 --model_dim_hidden 128 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key yacht__bs_-1__feature_mask__cosine_cyclic --exp_scheduler=cosine_cyclic --exp_optimizer_warmup_proportion 0.2 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2

## Breast Cancer
# Default
python run.py --data_set breast-cancer --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --model_num_heads 8 --model_stacking_depth 8 --exp_lr 5e-4 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000  --exp_gradient_clipping 1  --exp_batch_size -1 --model_dim_hidden 32 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key breast_cancer__dim_hidden_32__bs_-1__feature_mask --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Feature Mask 0.20
python run.py --data_set breast-cancer --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --model_num_heads 8 --model_stacking_depth 8 --exp_lr 5e-4 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000  --exp_gradient_clipping 1  --exp_batch_size -1 --model_dim_hidden 32 --model_augmentation_bert_mask_prob "dict(train=0.2, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key breast_cancer__dim_hidden_32__bs_-1__feature_mask_20perc --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Label Mask 0.50
python run.py --data_set breast-cancer --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --model_num_heads 8 --model_stacking_depth 8 --exp_lr 5e-4 --exp_scheduler flat_and_anneal --exp_num_total_steps 4000  --exp_gradient_clipping 1  --exp_batch_size -1 --model_dim_hidden 32 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key breast_cancer__dim_hidden_32__bs_-1__feature_mask__label_mask_50 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Label Mask 0.10
python run.py --data_set breast-cancer --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --model_num_heads 8 --model_stacking_depth 8 --exp_lr 5e-4 --exp_scheduler flat_and_anneal --exp_num_total_steps 20000  --exp_gradient_clipping 1  --exp_batch_size -1 --model_dim_hidden 32 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.1, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key breast_cancer__dim_hidden_32__bs_-1__feature_mask__label_mask_10 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 16 Heads
python run.py --data_set breast-cancer --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --model_num_heads 16 --model_stacking_depth 8 --exp_lr 5e-4 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000  --exp_gradient_clipping 1  --exp_batch_size -1 --model_dim_hidden 32 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key breast_cancer__dim_hidden_32__bs_-1__feature_mask__heads_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 16 Layers
python run.py --data_set breast-cancer --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --model_num_heads 8 --model_stacking_depth 16 --exp_lr 5e-4 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000  --exp_gradient_clipping 1  --exp_batch_size -1 --model_dim_hidden 32 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key breast_cancer__dim_hidden_32__bs_-1__feature_mask__layers_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# 16 Heads, 16 Layers
python run.py --data_set breast-cancer --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.5 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --model_num_heads 16 --model_stacking_depth 16 --exp_lr 5e-4 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000  --exp_gradient_clipping 1  --exp_batch_size -1 --model_dim_hidden 32 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key breast_cancer__dim_hidden_32__bs_-1__feature_mask__heads_16__layers_16 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2
# Cosine Cyclic LR Schedule
python run.py --data_set breast-cancer --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --model_num_heads 8 --model_stacking_depth 8 --exp_lr 5e-4 --exp_num_total_steps 2000  --exp_gradient_clipping 1  --exp_batch_size -1 --model_dim_hidden 32 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_checkpoint_key breast_cancer__dim_hidden_32__bs_-1__feature_mask__cosine_cyclic --exp_scheduler=cosine_cyclic --exp_optimizer_warmup_proportion 0.2 --exp_n_runs 10 --exp_test_perc 0.1 --exp_val_perc 0.2

### UCI Medium and Large Data

## Kick
python run.py --data_set kick --data_loader_nprocs=4 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 250000  --exp_gradient_clipping 1 --exp_batch_size 4096 --model_dim_hidden 64 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key kick__bs_4096__feature_mask__label_mask
## Poker Hand
python run.py --data_set poker-hand --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc False --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 200000 --exp_gradient_clipping 1 --exp_batch_size 4096 --model_dim_hidden 64 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key poker_hand__bs_4096__feature_mask__label_mask_0.5__class_balance --exp_batch_class_balancing True
## Income
python run.py --data_set income --data_loader_nprocs=2 --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 2000000 --exp_gradient_clipping 1 --exp_batch_size 2048 --model_dim_hidden 64 --model_augmentation_bert_mask_prob "dict(train=0.0, val=0.0, test=0.0)" --exp_tradeoff 0 --exp_tradeoff_annealing constant --model_label_bert_mask_prob "dict(train=0.15, val=0.0, test=0.0)" --exp_cache_cadence 1 --model_checkpoint_key income__bs_2048__label_mask
## Forest Cover
python run.py --data_set forest-cover --exp_eval_every_n 5 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.01 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --exp_print_every_nth_forward 1000 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 5e-3 --exp_scheduler polynomial_decay_warmup --exp_num_total_steps 800000 --exp_gradient_clipping 1 --exp_batch_size 1800 --model_dim_hidden 64 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --exp_cache_cadence 1 --model_label_bert_mask_prob "dict(train=0.5, val=0.0, test=0.0)" --model_checkpoint_key forest_cover__bs_2048__feature_mask__label_mask_0.5__poly_decay__class_balance --exp_batch_class_balancing True
## Higgs
python run.py --data_set higgs --data_loader_nprocs=4 --exp_eval_every_n 1 --exp_eval_every_epoch_or_steps epochs --exp_optimizer_warmup_proportion 0.7 --exp_optimizer lookahead_lamb --exp_azure_sweep True --metrics_auroc True --exp_print_every_nth_forward 100 --model_num_heads 8 --model_stacking_depth 8 --exp_lr 1e-3 --exp_scheduler flat_and_anneal --exp_num_total_steps 500000 --exp_gradient_clipping 1 --exp_batch_size 4096 --model_dim_hidden 64 --model_augmentation_bert_mask_prob "dict(train=0.15, val=0, test=0)" --exp_tradeoff 1 --exp_tradeoff_annealing cosine --model_checkpoint_key higgs__bs_4096__feature_mask
